config/routes.rb
Rails.application.routes.draw do

  get 'profiles/account' => 'profiles#account'

  devise_for :users
  get 'tags/:tag' => 'articles#index', as: :tag

  get 'info' => 'helps#info'

  root 'helps#info'

  resources :articles
    resources :comments
  get 'index'=>'articles#index'
  get 'show'=>'articles#show'
  get 'new'=>'articles#new'
  post 'new'=>'articles#create'
  post 'articles/:id' => "articles#show"
  get 'edit'=>'articles#edit'
  patch 'articles/:id' => 'articles#update'
  get 'delete' => 'articles#delete'
  post 'delete' => 'articles#destroy'
  get 'listindex' => 'articles#listindex'
  get 'indexall' => 'articles#indexall'

  get 'by_timing' => 'timinggs#by_timing'
  get 'daily' => 'timinggs#daily'
  get 'weekly' => 'timinggs#weekly'
  get 'biweekly' => 'timinggs#biweekly'
  get 'monthly' => 'timinggs#monthly'
  get 'quarterly' => 'timinggs#quarterly'
  get 'annually' => 'timinggs#annually'
  get 'onrequest' => 'timinggs#onrequest'
  get 'adhoc' => 'timinggs#adhoc'

  resources :categories
    resources :comments
  get 'index'=>'categories#index'
  get 'show'=>'categories#show'
  get 'new'=>'categories#new'
  post 'new'=>'categories#create'
  post 'categories/:id' => 'categories#show'
  get 'edit'=>'categories#edit'
  patch 'categories/:id' => 'categories#update'
  get 'categories/delete/:id' => 'categories#delete'
  post 'categories/delete/:id' => 'categories#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	has_attached_file :document, :default_url => "/images/:style/missing.png"
  	has_attached_file :shortcut, :default_url => "/images/:style/missing.png"
	has_attached_file :template, :default_url => "/images/:style/missing.png"
	has_attached_file :misc, :default_url => "/images/:style/missing.png"

	validates_presence_of	:title
	validates_presence_of	:timing
	validates_presence_of	:document
	validates_presence_of	:overview
	validates_presence_of	:reference
	validates_presence_of	:tag_list

 	acts_as_taggable

 	searchable do
 		text :title, :boost=>5
 		text :timing
 		text :team
 		text :reference
 		text :tag_list, :boost=>3
 	end

 	has_many :categorizations
 	has_many :category, :through=>:categorizations
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :delete]

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
    @search = Article.search do 
      fulltext params[:search]
    end
    @articles = @search.results
    end
  end

  def indexall
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]) do
      paginate(:page=>params[:page]||1, :per_page=>12)
    end
    else
    @search = Article.search do 
      fulltext params[:search]
      paginate(:page=>params[:page]||1, :per_page=>12)
    end
    @articles = @search.results
    end
  end

  def show
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @article = Article.find(params[:id])
    @categories = Category.all
    @source = @article.category_id
    @category = @article.category
    @comments = Comment.all
    @comment = Comment.new
  end

  def listindex
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
    @search = Article.search do 
      fulltext params[:search]
    end
    @articles = @search.results
    end
  end

  def new
    @article = Article.new
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Documentation has been succesfully created!"
      redirect_to(:action=>'show', :id=>@article.id)
    else
      render('new')
    end
  end

  def edit
    @article = Article.find(params[:id])
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @categories = Category.all
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:notice] = "Documentation was successfully updated!"
      redirect_to(:action=>'show', :id=>@article.id)
    else
      render('edit')
    end
  end

  def delete
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
    @article = Article.find(params[:id])
  end

  def destroy
    article = Article.find(params[:id]).destroy
    flash[:notice] = "This documentation [#{article.title}] has been destroyed"
    redirect_to(:action=>'index')
  end
  
  private

  def article_params
    params.require(:article).permit(:title, :category_id, :timing, :document, :template, :misc, :shortcut, :image, :team, :overview, :reference, :tag_list)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
      <% end %>
    </li>
  </ul>
<% end %>

<form class="form-horizontal">
<div class="form-box">
    <legend>Documentation Form</legend>
    <div class="form-group">
      <%= f.label(:title, "Title *") %><br />
      <%= f.text_field(:title, :placeholder=>"eg. BN Daily Queries", :class=>"formbox")%>
    </div>
    <div class="form-group">
      <%= f.label(:team, "Team") %><br />
      <%= f.text_field(:team, :placeholder=>"eg. Banking IFS Support", :class=>"formbox")%>
    </div>
    <div class="form-group">
      <%= f.label(:timing, "Timing *") %><br />
      <%= f.select(:timing, ['Daily', 'Weekly', 'BiWeekly', 'Monthly', 'Quarterly', 'Annually', 'On Request', 'Ad-hoc'])%>
    </div>
    <div class="form-group">
      <%= f.label(:category_id, "Category") %><br />
      <%= f.collection_select(:category_id, Category.order(:title), :id, :title)%>
    </div>
    <div class="form-group">
      <%= f.label(:overview, "Brief Overview *") %><br />
      <%= f.text_area(:overview, :placeholder=>"eg. BN Daily Queries", :class=>"textbox")%>
      <span class="help-block">Provide a quick high level overview of what this documentation is for. If possible, include brief steps.</span>
    </div>
    <div class="form-group">
      <%= f.label(:reference, "Reference *") %><br />
      <%= f.text_field(:reference, :placeholder=>"eg. Carita Liu", :class=>"formbox")%>
    </div>
</div>
<div class="form-box">
  <h4>File Uploading: For multiple files, please upload a .zip file</h4>
    <div class="form-group">
      <%= f.label(:document, "Official Documentation *") %>
      <%= f.file_field :document %>
    </div>
    <div class="form-group">
      <%= f.label(:shortcut, "unOfficial Shortcuts") %>
      <%= f.file_field :shortcut %>
    </div>
    <div class="form-group">
      <%= f.label(:template, "Template") %>
      <%= f.file_field :template %>
    </div>
    <div class="form-group">
      <%= f.label(:misc, "Misc Storage") %>
      <%= f.file_field :misc %>
    </div>
    <div class="form-group">
      <%= f.label(:image, "Screenshot") %>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label(:tag_list, "Tags* (seperated by commas)") %><br />
      <%= f.text_field(:tag_list, :placeholder=>"eg. Baycom6, IFS Support", value: @article.tag_list.join(","), :class=>"formbox")%>
    </div>
</div>
<div class="form-box">
  <%= submit_tag("Update Documentation") %>
  <div class=asterick><p>* mandatory field</p></div>
</div>
</form>

app/views/articles/_submenu_cat.html.erb
<div id="submenu">
  <h4>Categories Index</h4><br />
  <%= render 'submenu_cats', categories: @categories.roots %>
</div>

app/views/articles/_submenu_cats.html.erb
<ul>
  <% categories.each do |category| %>
    <li>
	    <%= link_to_unless_current category.title, category %>
	    <%= render 'submenu_cats', categories: category.children if category.children.present? %>
    </li>
  <% end %>
</ul>

app/views/articles/delete.html.erb
<% @page_title = "Delete article" %>

<div class="center">
<div class="articles delete">
  <h2>Delete Documentation</h2>

  <%= form_for(:article, :url => {:action => 'delete', :id => @article.id}) do |f| %>

    <p>Are you sure you want to permanently delete this Documentation?</p>

    <p class="reference-name"><%= @article.title %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Documentation", {:action => 'delete', :id => @article.id}) %>
    </div>

  <% end %>
</div>
</div>

app/views/articles/edit.html.erb
<% @page_title = "Update article" %>

<%= render 'submenu_cat' %>

<div class="articles edit">
	<div class='center'>
  		<h2>Edit Documentation</h2>
	</div>

  <%= form_for @article do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

  <% end %>
</div>

app/views/articles/index.html.erb
<% @page_title = "articles" %>


<div class="center">
  <h2>Documentation Articles</h2>
  <div class="righthand"><%= link_to("Create New Documentation", new_article_path) %></div>
  <br />
    <% @articles.each do |article| %>
      <div class="box"> 
        <h2><%= link_to(article.title, {:action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <div style="inline">
          <p><%= article.timing %></p>
          <p><%= article.team %></p>
        </div>
        <div id="indeximage">
          <% if article.image.present? %>
            <%= link_to image_tag(article.image(:medium), {:action=>'show', :id=>article.id}) %>
          <% else %>
            <br /><br /><br /><p>No Image (Please attached screenshot)</p><br /><br />
          <% end %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
</div>

app/views/articles/indexall.html.erb
<% @page_title = "articles" %>

<%= paginate @articles %>

<div class="center">
  <h2>Documentation Articles</h2>
  <div class="righthand"><%= link_to("Create New Documentation", new_article_path) %></div>
  <div class="lefthand"><%= link_to("List View", listindex_path) %></div>
  <br />
    <% @articles.each do |article| %>
      <div class="box"> 
        <h2><%= link_to(article.title, {:action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <div style="inline">
          <p><%= article.timing %></p>
          <p><%= article.team %></p>
        </div>
        <div id="indeximage">
          <% if article.image.present? %>
            <%= link_to image_tag(article.image(:medium), {:action=>'show', :id=>article.id}) %>
          <% else %>
            <br /><br /><br /><p>No Image (Please attached screenshot)</p><br /><br />
          <% end %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
</div>
<br />
<br />
<br />
<div class='righthanddelete2'><%= paginate @articles %></div>

app/views/articles/listindex.html.erb
<% @page_title = "articles" %>

<div class="center">
  <h2>All Documentation Articles</h2>
  <div class="righthand"><%= link_to("Create New Documentation", new_article_path) %></div>
  <div class="lefthand"><%= link_to("Tile View", articles_path) %></div>
  <br />
    <% @articles.each do |article| %>
      <div class="listbox"> 
        <h4><%= link_to(article.title, {:action=>'show', :id=>article.id}, :class => 'action show')%></h4>
          <p><%= article.timing %></p>
          <p><%= article.team %></p>
          <p>Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
</div>

app/views/articles/new.html.erb
<% @page_title = "New Documentation" %>

<%= render 'submenu_cat' %>

<div class="Article new">
	<div class="center">
  		<h2>Create New Documentation</h2>
  	</div>

  <%= form_for(:article, :url => {:action => 'create'}) do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

  <% end %>
</div>

app/views/articles/show.html.erb
<head>
<%= stylesheet_link_tag 'articles' %>
</head>

<%= render 'submenu_cat' %>

<div class='lefthand2'>
  <p> parent of category >  <%= link_to @category, category_path(:id=>@category)%>  > <%= link_to @article.category_id, category_path(:id=>@article.category_id) %></p>
</div>


<br />
<% @page_title = "Show Documentation" %>

<div style="text-align:left;">
  <div class="center">
    <h2><%= @article.title %></h2>
  </div>
  <br />
  <table summary="article detail view">
    <table align="center">
    <td width="150"></td>
      <tr>
        <th>Team</th>
        <td><%= @article.team %></td>
      </tr>
      <tr>
        <th>Timing</th>
        <td><%= @article.timing %></td>
      </tr>
      <tr>
        <th>Category</th>
        <td><%= link_to @article.category_id, category_path(:id=>@article.category_id)%></td>
      </tr>
      <tr>
        <th>Brief Overview</th>
        <td><%= @article.overview %></td>
      </tr>
      <tr>
        <th>Process</th>
        <td><%= link_to "Documentation", @article.document.url(:original, false) %></td>
      </tr>
      <tr>
        <th>Alternative</th>
        <% if @article.misc.present? %>
          <td><%= link_to "Shortcut", @article.shortcut.url(:original, false) %></td>
        <%else%>
          <td>None</td>
        <% end %>
      </tr>
      <tr>
        <th>Templates</th>
        <% if @article.misc.present? %>
          <td><%= link_to "Templates", @article.template.url(:original, false) %></td>
        <%else%>
          <td>None</td>
        <% end %>
      </tr>
      <tr>
        <th>Misc Storage</th>
        <% if @article.misc.present? %>
          <td><%= link_to "Misc Storage", @article.misc.url(:original, false) %></td>
        <%else%>
          <td>None</td>
        <% end %>
      </tr>
      <tr>
        <th>Reference</th>
        <td><%= @article.reference %></td>
      </tr>
      <tr>
        <th>Tags</th>
        <td><%= raw @article.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')%></td>
      </tr>
      <br />
      <br />
      <td class="actions">
          <%= link_to("Edit", {:action => 'edit', :id => @article.id}, :class => 'action edit') %>
          <%= link_to("Delete", {:action => 'delete', :id => @article.id}, :class => 'action delete')%>
      </td>
    </table>
  </table>

<div class="center">
  <br />
  <% if @article.image.present? %>
    <%= image_tag @article.image.url(:medium)%>
  <% else %>
    <br /><br /><p>No Image (Please attached screenshot)</p>
  <% end %>
</div>
<br />
<br />
<br />
<div class="commento">
  <%= render "comments/commenta" %>
  <%= render "comments/forma" %>
</div>