config/routes.rb
Rails.application.routes.draw do

  get 'profiles/account' => 'profiles#account'

  devise_for :users
  get 'tags/:tag' => 'articles#index', as: :tag

  get 'info' => 'helps#info'

  root 'helps#info'

  resources :articles
    resources :comments
  get 'index'=>'articles#index'
  get 'show'=>'articles#show'
  get 'new'=>'articles#new'
  post 'new'=>'articles#create'
  post 'articles/:id' => "articles#show"
  get 'edit'=>'articles#edit'
  patch 'articles/:id' => 'articles#update'
  get 'delete' => 'articles#delete'
  post 'delete' => 'articles#destroy'
  get 'listindex' => 'articles#listindex'
  get 'indexall' => 'articles#indexall'

  get 'by_timing' => 'timinggs#by_timing'
  get 'daily' => 'timinggs#daily'
  get 'weekly' => 'timinggs#weekly'
  get 'biweekly' => 'timinggs#biweekly'
  get 'monthly' => 'timinggs#monthly'
  get 'quarterly' => 'timinggs#quarterly'
  get 'annually' => 'timinggs#annually'
  get 'onrequest' => 'timinggs#onrequest'
  get 'adhoc' => 'timinggs#adhoc'

  resources :categories
    resources :comments
  get 'index'=>'categories#index'
  get 'show'=>'categories#show'
  get 'new'=>'categories#new'
  post 'new'=>'categories#create'
  post 'categories/:id' => 'categories#show'
  get 'edit'=>'categories#edit'
  patch 'categories/:id' => 'categories#update'
  get 'categories/delete/:id' => 'categories#delete'
  post 'categories/delete/:id' => 'categories#destroy'

end

app/models/timingg.rb
class Timingg < ActiveRecord::Base

	 searchable do
 		text :title, :boost=>5
 		text :timing
 		text :team
 		text :reference
 		text :tag_list, :boost=>3
 	end
 	
end

app/controllers/timinggs_controller.rb
class TiminggsController < ApplicationController

  def by_timing
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  end

  def daily
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def weekly
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def biweekly
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def monthly
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def quarterly
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def annually
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def onrequest
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

  def adhoc
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
  @articles = Article.all
  end

end

app/helpers/timinggs_helper.rb
module TiminggsHelper
end

app/views/timinggs/adhoc.html.erb
<div style="text-align:center;">
  <h2>Ad-hoc Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Ad-hoc' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/annually.html.erb
<div style="text-align:center;">
  <h2>Annual Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Annually' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/biweekly.html.erb
<div style="text-align:center;">
  <h2>BiWeekly Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'BiWeekly' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/by_timing.html.erb
	<div class='center'>
		<h1>Tasks by Timing</h1>
	</div>

	<%= button_to('Daily', daily_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('Weekly', weekly_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('BiWeekly', biweekly_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('Monthly', monthly_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('Quarterly', quarterly_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('Annual', annually_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('On Request', onrequest_path, :method=>'get', :class => 'bigolbutton')  %>
	<%= button_to('Ad-hoc', adhoc_path, :method=>'get', :class => 'bigolbutton')  %>

app/views/timinggs/daily.html.erb
<div style="text-align:center;">
  <h2>Daily Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Daily' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/monthly.html.erb
<div style="text-align:center;">
  <h2>Monthly Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Monthly' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/onrequest.html.erb
<div style="text-align:center;">
  <h2>On Request Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'On Request' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/quarterly.html.erb
<div style="text-align:center;">
  <h2>Quarterly Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Quaterly' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/timinggs/weekly.html.erb
<div style="text-align:center;">
  <h2>Weekly Tasks</h2>
  <br />
    <% @articles.each do |article| %>
    <% if article.timing == 'Weekly' %>
      <div class='box'>
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <p><%= article.timing %></p>
        <p><%= article.team %></p>
        <div id="indeximage">
          <%= link_to image_tag(article.image(:medium)) %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>