config/routes.rb
Rails.application.routes.draw do

  get 'profiles/account' => 'profiles#account'

  devise_for :users
  get 'tags/:tag' => 'articles#index', as: :tag

  get 'info' => 'helps#info'

  root 'helps#info'

  resources :articles
    resources :comments
  get 'index'=>'articles#index'
  get 'show'=>'articles#show'
  get 'new'=>'articles#new'
  post 'new'=>'articles#create'
  post 'articles/:id' => "articles#show"
  get 'edit'=>'articles#edit'
  patch 'articles/:id' => 'articles#update'
  get 'delete' => 'articles#delete'
  post 'delete' => 'articles#destroy'
  get 'listindex' => 'articles#listindex'
  get 'indexall' => 'articles#indexall'

  get 'by_timing' => 'timinggs#by_timing'
  get 'daily' => 'timinggs#daily'
  get 'weekly' => 'timinggs#weekly'
  get 'biweekly' => 'timinggs#biweekly'
  get 'monthly' => 'timinggs#monthly'
  get 'quarterly' => 'timinggs#quarterly'
  get 'annually' => 'timinggs#annually'
  get 'onrequest' => 'timinggs#onrequest'
  get 'adhoc' => 'timinggs#adhoc'

  resources :categories
    resources :comments
  get 'index'=>'categories#index'
  get 'show'=>'categories#show'
  get 'new'=>'categories#new'
  post 'new'=>'categories#create'
  post 'categories/:id' => 'categories#show'
  get 'edit'=>'categories#edit'
  patch 'categories/:id' => 'categories#update'
  get 'categories/delete/:id' => 'categories#delete'
  post 'categories/delete/:id' => 'categories#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :article, :through=> :categorizations

	has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :delete]

  def index
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @categories = Category.all
    #@subcats = Category.all.collect{|x| x.category_id.present? }
  end

  def show
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @category = Category.find(params[:id])
    @categories = Category.all
    @articles = Article.all
    @comments = Comment.all
    @comment = Comment.new
  end

  def new
    @category = Category.new
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "New Category Successfully Created!"
      redirect_to(categories_path)
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
    if params[:search]
      search_param = CGI::escapeHTML(params[:search])
      redirect_to("/articles?search=#{search_param}&commit=Search")
      return
    end
    @categories = Category.all
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Category was successfully updated!"
      redirect_to(:action=>'show', :id=>@category.id)
    else
      render('edit')
    end
  end

  def delete
  if params[:search]
    search_param = CGI::escapeHTML(params[:search])
    redirect_to("/articles?search=#{search_param}&commit=Search")
    return
  end
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.find(params[:id]).destroy
    flash[:notice] = "The category has been destroyed"
    redirect_to(:action=>'index')
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :parent_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <ul>
    <% @category.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
      <% end %>
    </li>
  </ul>
<% end %>

<form class="form-horizontal">
<div class="form-box">
    <legend>New Category Form</legend>
    <div class="form-group">
      <%= f.label(:title, "Title") %><br />
      <%= f.text_field(:title, :placeholder=>"eg. Audit", :class=>"formbox")%>
    </div>
    <div class="form-group">
      <%= f.label(:description, "Description") %><br />
      <%= f.text_area(:description, :class=>"textbox")%>
      <span class="help-block">What does this category cover? Related tasks will be associated with this category.</span>
    </div>
    <div class="form-group">
      <%= f.label(:parent_id, "Sub-Category of") %><br />
      <%= f.collection_select(:parent_id, Category.order(:title), :id, :title, include_blank: true )%>
    </div>
</div>
<div class="form-box">
  <%= submit_tag("Create") %>
</div>
</form>

app/views/categories/_submenu_cat.html.erb
<div id="submenu">
  <h4>Categories Index</h4><br />
  <%= render 'submenu_cats', categories: @categories.roots %>
</div>

app/views/categories/_submenu_cats.html.erb
<ul>
  <% categories.each do |category| %>
    <li>
	    <%= link_to_unless_current category.title, category %>
	    <%= render 'submenu_cats', categories: category.children if category.children.present? %>
    </li>
  <% end %>
</ul>

app/views/categories/delete.html.erb
<% @page_title = "Delete article" %>

<div class="center">
<div class="articles delete">
  <h2>Delete Category</h2>

  <%= form_for(:category, :url => {:action => 'delete', :id => @category.id}) do |f| %>

    <p>Are you sure you want to permanently delete this Category?</p>

    <p class="reference-name"><%= @category.title %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Category", {:action => 'delete', :id => @category.id}) %>
    </div>

  <% end %>
</div>
</div>

app/views/categories/edit.html.erb
<% @page_title = "Update category" %>


<%= render 'submenu_cat' %>

<div class="articles edit">
	<div class='center'>
  		<h2>Edit Category</h2>
	</div>

  <%= form_for @category do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

  <% end %>
</div>

app/views/categories/index.html.erb
<h1>Tasks by Categories</h1>


<%= render 'submenu_cat' %>

<div class='righthand'><%= link_to("Add Category", new_category_path) %></div><br />

<div class='spacer'>
    <% @categories.each do |category| %>
    	<% unless category.parent.present? %>
        	<%= button_to(category.title, {:action=>'show', :id=>category.id}, :class => 'bigolbutton2')%>
        <% end %>
    <% end %>
</div>

app/views/categories/new.html.erb
<% @page_title = "New Category" %>


<%= render 'submenu_cat' %>

<div class="Article new">
	<div class="center">
  		<h2>Create New Category</h2>
  	</div>

  <%= form_for(:category, :url => {:action => 'create'}) do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

  <% end %>
</div>

app/views/categories/show.html.erb
<%= render 'submenu_cat' %>

<div class='center'><h2><%= @category.title %></h1></div><br />

  <div class="righthand">
    <%= link_to("New Documentation", new_article_path) %><br /><%= link_to("New Sub-Category", new_category_path) %>
  </div>

<div class="subcats">
  <h2>Sub-Categories</h2>
  <% @category.children.each do |category| %>
      <div class="listbox2">
        <h2><%= link_to(category.title, category_path(:id=>category.id)) %></h2>
      </div>
  <% end %>
</div>
<br />
<br />
<br />
<br />
<br />

<div class="subcats">
  <br />
    <h2><%= @category.title%> Related Tasks </h2>
    <% @articles.each do |article| %>
    <% if article.category_id == @category.id %>
      <div class="box3"> 
        <h2><%= link_to(article.title, {:controller=>'articles', :action=>'show', :id=>article.id}, :class => 'action show')%></h2>
        <div style="inline">
          <p><%= article.timing %></p>
          <p><%= article.team %></p>
        </div>
        <div id="indeximage">
          <% if article.image.present? %>
            <%= link_to image_tag(article.image(:medium), {:action=>'show', :id=>article.id}) %>
          <% else %>
            <br /><br /><br /><p>No Image (Please attached screenshot)</p><br /><br />
          <% end %>
        </div>
        <p><br />Tags: <%= article.tag_list %></p>
      </div>
    <% end %>
    <% end %>
</div>

<br />
<br />
<br />
<br />
<div class='righthanddelete'>
	<%= link_to("Edit This Category", {:action => 'edit', :id => @category.id}, :class => 'action edit') %><br />
	<%= link_to("Delete This Category", {:controller=>'categories', :action=>'delete', :id=>@category.id}) %>
</div>
<br />
<br />
<br />
<div class="commento">
  <%= render "comments/commentc" %>
  <%= render "comments/formc" %>
</div>