config/routes.rb
Rails.application.routes.draw do

  get 'profiles/account' => 'profiles#account'

  devise_for :users
  get 'tags/:tag' => 'articles#index', as: :tag

  get 'info' => 'helps#info'

  root 'helps#info'

  resources :articles
    resources :comments
  get 'index'=>'articles#index'
  get 'show'=>'articles#show'
  get 'new'=>'articles#new'
  post 'new'=>'articles#create'
  post 'articles/:id' => "articles#show"
  get 'edit'=>'articles#edit'
  patch 'articles/:id' => 'articles#update'
  get 'delete' => 'articles#delete'
  post 'delete' => 'articles#destroy'
  get 'listindex' => 'articles#listindex'
  get 'indexall' => 'articles#indexall'

  get 'by_timing' => 'timinggs#by_timing'
  get 'daily' => 'timinggs#daily'
  get 'weekly' => 'timinggs#weekly'
  get 'biweekly' => 'timinggs#biweekly'
  get 'monthly' => 'timinggs#monthly'
  get 'quarterly' => 'timinggs#quarterly'
  get 'annually' => 'timinggs#annually'
  get 'onrequest' => 'timinggs#onrequest'
  get 'adhoc' => 'timinggs#adhoc'

  resources :categories
    resources :comments
  get 'index'=>'categories#index'
  get 'show'=>'categories#show'
  get 'new'=>'categories#new'
  post 'new'=>'categories#create'
  post 'categories/:id' => 'categories#show'
  get 'edit'=>'categories#edit'
  patch 'categories/:id' => 'categories#update'
  get 'categories/delete/:id' => 'categories#delete'
  post 'categories/delete/:id' => 'categories#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>CGI Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CGI Wiki</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to("Documentation", indexall_path, :class => 'action show')%></li>
        <li><%= link_to("Categories", categories_path, :class => 'action show')%></li>
        <li><%= link_to("Timing", by_timing_path, :class => 'action show')%></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to("Forum", info_path, :class => 'action show')%></li>
            <li><%= link_to("Notifications", info_path, :class => 'action show')%></li>
            <li><%= link_to("Inbox", info_path, :class => 'action show')%></li>
            <li class="divider"></li>
            <% if user_signed_in? %>
              <li><%= link_to("Profile", profiles_account_path, :class => 'action show')%></li>
            <% else %>
              <li><%= link_to("Profile", new_user_session_path, :class => 'action show')%></li>
            <% end %>
            <li><%= link_to("Favorites", info_path, :class => 'action show')%></li>
            <li class="divider"></li>
            <li><%= link_to("Log Out", info_path, :class => 'action show')%></li>
          </ul>
        </li>
        <li><%= link_to("Help", info_path, :class => 'action show')%></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <%= form_tag articles_path, :method => :get do %>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name=>nil %>
        <%end%>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to("Log Out", destroy_user_session_path, method: :delete)%></li>
        <% else %>
          <li><%= link_to("Log In", new_user_session_path, :class => 'action show')%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  <br />
<% if notice.present? %>
  <div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h2>Notice</h2>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
	<%= yield %>
</body>
</html>